name: inprize
description: Instagram giveaway randomizer.
publish_to: 'none'
version: 1.0.4+4

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_facebook_auth: ^4.4.1+1
  url_launcher: ^6.1.5
  stack_appodeal_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher-icon.png"

flutter:
  uses-material-design: false

  assets:
    - assets/icons/launcher-icon.png
    - assets/icons/facebook.svg
